%%{init: { "theme": "base", "themeVariables": { "lineColor": "#ffffff" } }}%%
graph TB
    subgraph Client_Side
        Browser[User Browser]
    end

    subgraph "Application & Logic"
        Streamlit[Streamlit Cloud]
        Snowpark[Snowpark Python API]
    end

    subgraph Snowflake_Data_Cloud
        subgraph Compute
            WH[Compute Warehouse]
        end
        
        subgraph Data_Storage
            DB[(StockPulse DB)]
            Stage[Internal Stages]
        end
        
        subgraph AI_Services
            Cortex[Cortex AI / ML Functions]
        end
    end

    subgraph External_Services
        Slack[Slack API]
        SMTP[SMTP Server]
    end

    Browser -- HTTPS --> Streamlit
    Streamlit -- Streamlit Connector --> WH
    Snowpark -- Dataframe API --> WH
    WH -- SQL/Python --> DB
    
    Streamlit -- Webhook --> Slack
    Streamlit -- SMTP --> SMTP
    WH -- Call --> Cortex
    Snowpark -- Trigger --> Cortex
